#!/bin/sh

set -e errexit
ulimit -n 10240

rm -rf dist
ANIMATIONS_DISABLED=$ANIMATIONS_DISABLED node_modules/.bin/webpack --stats --progress --config ./webpack/prod.config.js

# from this point on if something goes wrong we don't want to immediately exit
# because we have to make sure we tidy up the server properly and kill the process
set +e errexit

./script/dump-html 'dist'
DUMP_EXIT=$?

set -e errexit

if [ $DUMP_EXIT -eq 0 ]; then
  cp -R public/* dist
else
  exit $DUMP_EXIT
fi
