#!/bin/bash
# Usage: script/e2e

PORT='4402'

# if something is on our port, bail out and shout
echo exit | nc localhost $PORT
if [ $? -eq 0 ]; then
  echo "something is already running on $PORT"
  exit 1
fi

# Quit on errors.
set -e errexit

# Build production application to dist/ directory.
ANIMATIONS_DISABLED=true ./script/build-prod

# Serve production ready application with a static http-server on a specific port. Pipe all server output to log file.
./node_modules/.bin/serve -p $PORT dist/ &>.e2e_server_log &
# Gets server pid to kill it later.
SERVER_PID=$!

# wait for the server to be up and running
while ! echo exit | nc localhost $PORT; do sleep 1; done

# at this point on, we want it to not exit even if protractor fails
# so we can kill the server process
set +e errexit

# Runs protractor with specific config object.
PORT=$PORT ./node_modules/.bin/protractor config/protractor.config.js

# Gets protractor exit code.
PROTRACTOR_EXIT=$?

# Kills static content server.
kill $SERVER_PID

# Exits with the exit code returned by protractor.
exit $PROTRACTOR_EXIT
